<!DOCTYPE html>
<html>
<body>
  

<h2 style="color:blue;text-align:center; background-color: orange; height: 100px; font-size:  40px; margin-top: -6px;margin-left:px;" >Date and time </h2>

<button type="button" style=" background-color: yellow; text-align: center; width:  200px; height: 200px; font-size: 30px; margin-left: 550px;" 

 onmouseover ="document.getElementById('mydemo').innerHTML = Date()">
 HOVERON ME I WILL SHOW YOU TIME AND DATE .</button>

 <p id="mydemo" style="font-size: 30px; background-color: orange; 
 text-align: center;"></p>

</body>
</html> 
